exp=s2st.fr-en.comspeech-zs
python fairseq/fairseq_cli/train.py data/comspeech/cvss_fr_en/s2s \
    --user-dir ComSpeech \
    --validate-task s2st --multiscale-modeling \
    --st-data data/comspeech/cvss_fr_en/speech2unigram --tts-data data/comspeech/cvss_x_en/tts/ \
    --save-dir ComSpeech/checkpoints/$exp --tensorboard-logdir ComSpeech/checkpoints/$exp \
    --config-yaml config.yaml --multitask-config-yaml config_multiscale.yaml --train-subset train --valid-subset dev \
    --num-workers 8 --max-update 100000 \
    --task comspeech_task --criterion comspeech_criterion --arch s2s_conformer_fastspeech2 \
    --encoder-layers 12 --encoder-embed-dim 256 --encoder-ffn-embed-dim 2048 --encoder-attention-heads 4 \
    --decoder-layers 4  --decoder-embed-dim 512 --decoder-ffn-embed-dim 2048 --decoder-attention-heads 8 \
    --tts-encoder-layers 4 --tts-encoder-embed-dim 256 --tts-encoder-attention-heads 2 \
    --tts-decoder-layers 4 --tts-decoder-embed-dim 256 --tts-decoder-attention-heads 2 \
    --adaptor-encoder-layers 0 --adaptor-decoder-layers 4 --ctc-upsample 5 \
    --share-decoder-input-output-embed \
    --st-loss-weight 1.0 --tts-loss-weight 1.0 --w2p-dp-loss-weight 1.0 --match-loss-weight 1.0 --label-smoothing 0.1 \
    --tctr-loss-weight 1.0 --tctr-temp 0.1 --metric-ctr l1 \
    --clip-norm 5.0 --n-frames-per-step 1 --fp16 \
    --dropout 0.3 --attention-dropout 0.3 --relu-dropout 0.3 \
    --lr 1e-3 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-7 --warmup-updates 4000 \
    --optimizer adam --adam-betas "(0.9,0.98)" \
    --ddp-backend=legacy_ddp --patience 10 \
    --max-tokens-st 20000 --batch-size-tts 32 \
    --max-tokens 40000 \
    --st-sample-ratio 1 --tts-sample-ratio 1 \
    --no-progress-bar --log-format json --log-interval 100 \
    --required-batch-size-multiple 1 \
    --save-interval 1 --save-interval-updates 2000 \
    --validate-interval 1000 --validate-interval-updates 2000 \
    --keep-best-checkpoints 5 \
    --keep-interval-updates 5 --keep-last-epochs 5 \
    --attn-type espnet --pos-enc-type rel_pos \
    --load-pretrained-s2t-from ComSpeech/checkpoints/st.cvss.fr-en.ctc/checkpoint_best.pt \
    --load-pretrained-ctc-from ComSpeech/checkpoints/st.cvss.fr-en.ctc/checkpoint_best.pt \
    --load-pretrained-fastspeech-from ComSpeech/checkpoints/tts.fastspeech2.cvss-x-en/checkpoint_best.pt \
    --seed 1 --update-freq 4